"""
career_catalog.py
Flat list of careers used exclusively by the unified scoring engine.
Each entry has full metadata for all 5 scoring components.
DO NOT modify aptitude-backend/career_mapping.py — that is unchanged.
"""

CAREER_CATALOG = [

    # ─── Investigative Primary ─────────────────────────────────────────────────

    {
        "title": "Data Scientist",
        "salary": "₹8–25 LPA",
        "riasec_primary": "I",
        "riasec_secondary": "R",
        "streams": ["pcm", "pcmb"],
        "subject_weights": {
            "mathematics": 0.9,
            "computerScience": 0.85,
            "physics": 0.5,
            "statistics": 0.7,
        },
        "workstyle_weights": {
            "researching": 0.9,
            "building": 0.4,
            "structured": 0.5,
        },
        "priority_alignment": ["Intellectual Challenge", "High Salary"],
        "sector": "private",
        "cost_level": "medium",
        "requires_relocation": False,
        "reason": "Your analytical nature and curiosity are exactly what data science rewards. Data Scientists spend their days finding patterns in complex datasets and building models that power real decisions — the kind of deep, focused problem-solving your profile points toward.",
    },

    {
        "title": "Software Engineer",
        "salary": "₹7–30 LPA",
        "riasec_primary": "I",
        "riasec_secondary": "R",
        "streams": ["pcm", "pcmb"],
        "subject_weights": {
            "mathematics": 0.85,
            "computerScience": 0.95,
            "physics": 0.4,
        },
        "workstyle_weights": {
            "researching": 0.6,
            "building": 0.8,
            "structured": 0.6,
        },
        "priority_alignment": ["High Salary", "Intellectual Challenge", "Work Life Balance"],
        "sector": "private",
        "cost_level": "medium",
        "requires_relocation": False,
        "reason": "Logical problem solving is the daily currency of software engineering. Engineers design systems, debug complex issues, and build tools that millions of people use — a career that rewards the kind of structured analytical thinking your profile shows.",
    },

    {
        "title": "Research Scientist",
        "salary": "₹6–18 LPA",
        "riasec_primary": "I",
        "riasec_secondary": "I",
        "streams": ["pcm", "pcb", "pcmb"],
        "subject_weights": {
            "physics": 0.8,
            "chemistry": 0.8,
            "biology": 0.7,
            "mathematics": 0.7,
        },
        "workstyle_weights": {
            "researching": 0.95,
            "building": 0.3,
            "structured": 0.5,
        },
        "priority_alignment": ["Intellectual Challenge", "Social Impact"],
        "sector": "study",
        "cost_level": "low",
        "requires_relocation": True,
        "reason": "Your curiosity and drive to understand how things work are the defining traits of a research scientist. Research Scientists spend years exploring unknowns — running experiments, publishing findings, and pushing the boundaries of human knowledge.",
    },

    {
        "title": "Data Analyst",
        "salary": "₹5–18 LPA",
        "riasec_primary": "I",
        "riasec_secondary": "C",
        "streams": ["pcm", "pcmb", "comm"],
        "subject_weights": {
            "mathematics": 0.85,
            "computerScience": 0.7,
            "economics": 0.6,
            "accountancy": 0.4,
        },
        "workstyle_weights": {
            "researching": 0.8,
            "structured": 0.7,
            "building": 0.3,
        },
        "priority_alignment": ["Intellectual Challenge", "Job Stability"],
        "sector": "private",
        "cost_level": "medium",
        "requires_relocation": False,
        "reason": "Turning raw numbers into actionable business insights is the core of data analysis. Data Analysts work at the intersection of logic and communication — finding the story inside data that organisations use to make better decisions.",
    },

    {
        "title": "Biomedical Engineer",
        "salary": "₹6–20 LPA",
        "riasec_primary": "I",
        "riasec_secondary": "R",
        "streams": ["pcb", "pcmb"],
        "subject_weights": {
            "biology": 0.85,
            "chemistry": 0.75,
            "physics": 0.7,
            "mathematics": 0.6,
        },
        "workstyle_weights": {
            "researching": 0.8,
            "building": 0.7,
            "structured": 0.5,
        },
        "priority_alignment": ["Social Impact", "Intellectual Challenge"],
        "sector": "private",
        "cost_level": "medium",
        "requires_relocation": False,
        "reason": "Combining engineering principles with medical science to solve real healthcare problems is the heart of biomedical engineering. Biomedical Engineers design medical devices, prosthetics, and diagnostic tools that improve and save lives.",
    },

    {
        "title": "Environmental Scientist",
        "salary": "₹5–15 LPA",
        "riasec_primary": "I",
        "riasec_secondary": "R",
        "streams": ["pcb", "pcmb"],
        "subject_weights": {
            "biology": 0.85,
            "chemistry": 0.8,
            "geography": 0.6,
            "physics": 0.4,
        },
        "workstyle_weights": {
            "researching": 0.85,
            "building": 0.4,
            "helping": 0.5,
        },
        "priority_alignment": ["Social Impact", "Intellectual Challenge"],
        "sector": "govt",
        "cost_level": "low",
        "requires_relocation": True,
        "reason": "Studying how ecosystems function and how human activity affects them is at the core of environmental science. Environmental Scientists gather field data, analyse pollution and climate patterns, and inform the policies that protect our planet.",
    },

    {
        "title": "Psychologist",
        "salary": "₹4–18 LPA",
        "riasec_primary": "I",
        "riasec_secondary": "S",
        "streams": ["pcb", "arts"],
        "subject_weights": {
            "biology": 0.6,
            "history": 0.5,
            "politicalScience": 0.4,
        },
        "workstyle_weights": {
            "researching": 0.75,
            "helping": 0.85,
            "creative": 0.4,
        },
        "priority_alignment": ["Social Impact", "Intellectual Challenge"],
        "sector": "private",
        "cost_level": "medium",
        "requires_relocation": False,
        "reason": "Understanding how the mind works and helping people navigate mental and emotional challenges defines the psychologist's work. Psychologists apply evidence-based methods to assess, diagnose, and support people through clinical, educational, or research settings.",
    },

    {
        "title": "UX Researcher",
        "salary": "₹7–22 LPA",
        "riasec_primary": "I",
        "riasec_secondary": "A",
        "streams": ["pcm", "pcmb", "arts", "comm"],
        "subject_weights": {
            "computerScience": 0.6,
            "mathematics": 0.5,
            "history": 0.3,
        },
        "workstyle_weights": {
            "researching": 0.85,
            "creative": 0.7,
            "helping": 0.6,
        },
        "priority_alignment": ["Intellectual Challenge", "Creative Freedom"],
        "sector": "private",
        "cost_level": "medium",
        "requires_relocation": False,
        "reason": "UX Research sits at the intersection of analytical thinking and human empathy. UX Researchers design studies, conduct user interviews, and synthesise findings to make digital products intuitive — combining rigorous method with creative insight.",
    },

    # ─── Realistic Primary ─────────────────────────────────────────────────────

    {
        "title": "Mechanical Engineer",
        "salary": "₹5–18 LPA",
        "riasec_primary": "R",
        "riasec_secondary": "I",
        "streams": ["pcm", "pcmb"],
        "subject_weights": {
            "physics": 0.9,
            "mathematics": 0.85,
            "chemistry": 0.5,
        },
        "workstyle_weights": {
            "building": 0.9,
            "researching": 0.5,
            "structured": 0.6,
        },
        "priority_alignment": ["Job Stability", "Intellectual Challenge"],
        "sector": "private",
        "cost_level": "medium",
        "requires_relocation": False,
        "reason": "Designing, analysing, and manufacturing physical systems is what mechanical engineers do every day. This career rewards practical intelligence and the ability to turn abstract physics into machines, engines, and systems that actually work in the real world.",
    },

    {
        "title": "Civil Engineer",
        "salary": "₹5–16 LPA",
        "riasec_primary": "R",
        "riasec_secondary": "I",
        "streams": ["pcm", "pcmb"],
        "subject_weights": {
            "mathematics": 0.85,
            "physics": 0.8,
            "geography": 0.4,
        },
        "workstyle_weights": {
            "building": 0.9,
            "structured": 0.7,
            "researching": 0.4,
        },
        "priority_alignment": ["Job Stability", "Social Impact"],
        "sector": "govt",
        "cost_level": "low",
        "requires_relocation": True,
        "reason": "Bridges, dams, roads, and buildings — civil engineers design and oversee the infrastructure that holds society together. This career combines spatial reasoning, mathematics, and hands-on site management to create lasting physical structures.",
    },

    {
        "title": "Electrical Engineer",
        "salary": "₹4–20 LPA",
        "riasec_primary": "R",
        "riasec_secondary": "I",
        "streams": ["pcm", "pcmb"],
        "subject_weights": {
            "physics": 0.9,
            "mathematics": 0.85,
            "computerScience": 0.5,
        },
        "workstyle_weights": {
            "building": 0.85,
            "researching": 0.5,
            "structured": 0.6,
        },
        "priority_alignment": ["Job Stability", "Intellectual Challenge"],
        "sector": "private",
        "cost_level": "medium",
        "requires_relocation": False,
        "reason": "Designing electrical systems, circuits, and power infrastructure that keep the modern world running is the electrical engineer's core work. From power grids to embedded electronics, this field rewards technical precision and hands-on problem solving.",
    },

    {
        "title": "Architect",
        "salary": "₹5–20 LPA",
        "riasec_primary": "R",
        "riasec_secondary": "A",
        "streams": ["pcm", "pcmb"],
        "subject_weights": {
            "mathematics": 0.8,
            "physics": 0.6,
        },
        "workstyle_weights": {
            "building": 0.8,
            "creative": 0.85,
            "structured": 0.5,
        },
        "priority_alignment": ["Creative Freedom", "Intellectual Challenge"],
        "sector": "private",
        "cost_level": "high",
        "requires_relocation": False,
        "reason": "Architecture is where design meets engineering — creating spaces that are both structurally sound and aesthetically powerful. Architects design buildings from initial concept through construction, balancing artistic vision with practical constraints.",
    },

    {
        "title": "Doctor (MBBS)",
        "salary": "₹6–25 LPA",
        "riasec_primary": "R",
        "riasec_secondary": "S",
        "streams": ["pcb", "pcmb"],
        "subject_weights": {
            "biology": 0.95,
            "chemistry": 0.9,
            "physics": 0.5,
        },
        "workstyle_weights": {
            "helping": 0.9,
            "building": 0.5,
            "researching": 0.5,
        },
        "priority_alignment": ["Social Impact", "Job Stability", "High Salary"],
        "sector": "private",
        "cost_level": "medium",
        "requires_relocation": False,
        "reason": "Medicine combines deep scientific knowledge with direct human impact. Doctors diagnose illness, treat patients, and make critical decisions daily — a career for those who want rigorous intellectual challenge and the profound satisfaction of helping people heal.",
    },

    {
        "title": "Physiotherapist",
        "salary": "₹4–12 LPA",
        "riasec_primary": "R",
        "riasec_secondary": "S",
        "streams": ["pcb", "pcmb"],
        "subject_weights": {
            "biology": 0.9,
            "chemistry": 0.6,
            "physics": 0.5,
        },
        "workstyle_weights": {
            "helping": 0.9,
            "building": 0.6,
            "structured": 0.5,
        },
        "priority_alignment": ["Social Impact", "Work Life Balance"],
        "sector": "private",
        "cost_level": "medium",
        "requires_relocation": False,
        "reason": "Physiotherapists help patients recover movement and manage pain using evidence-based physical techniques. It is a career that combines biological knowledge with hands-on therapeutic skill and the genuine satisfaction of watching people regain their mobility.",
    },

    # ─── Artistic Primary ──────────────────────────────────────────────────────

    {
        "title": "UI/UX Designer",
        "salary": "₹6–22 LPA",
        "riasec_primary": "A",
        "riasec_secondary": "I",
        "streams": ["pcm", "pcmb", "arts", "comm"],
        "subject_weights": {
            "computerScience": 0.7,
            "mathematics": 0.4,
        },
        "workstyle_weights": {
            "creative": 0.9,
            "researching": 0.6,
            "building": 0.5,
        },
        "priority_alignment": ["Creative Freedom", "Intellectual Challenge", "High Salary"],
        "sector": "private",
        "cost_level": "medium",
        "requires_relocation": False,
        "reason": "UI/UX Design is where aesthetic sensibility meets user psychology. Designers craft the visual and interactive experience of apps and websites — solving real problems with creative solutions that make digital products feel intuitive and beautiful.",
    },

    {
        "title": "Graphic Designer",
        "salary": "₹4–15 LPA",
        "riasec_primary": "A",
        "riasec_secondary": "E",
        "streams": ["arts", "pcm", "comm"],
        "subject_weights": {
            "computerScience": 0.4,
        },
        "workstyle_weights": {
            "creative": 0.95,
            "building": 0.5,
            "leading": 0.3,
        },
        "priority_alignment": ["Creative Freedom", "Work Life Balance"],
        "sector": "private",
        "cost_level": "low",
        "requires_relocation": False,
        "reason": "Graphic designers communicate ideas visually — through logos, layouts, illustrations, and brand identities. This is a career for people who think in images, have a strong sense of composition and colour, and want their creativity to drive their work.",
    },

    {
        "title": "Film Director / Content Creator",
        "salary": "₹6–30 LPA",
        "riasec_primary": "A",
        "riasec_secondary": "E",
        "streams": ["arts", "comm"],
        "subject_weights": {
            "history": 0.4,
            "politicalScience": 0.3,
        },
        "workstyle_weights": {
            "creative": 0.95,
            "leading": 0.7,
            "helping": 0.4,
        },
        "priority_alignment": ["Creative Freedom", "Social Impact"],
        "sector": "entrepreneur",
        "cost_level": "low",
        "requires_relocation": False,
        "reason": "Film direction and content creation are about bringing stories and ideas to life for an audience. Directors and creators lead teams, make hundreds of decisions every day, and translate creative vision into compelling visual narratives.",
    },

    {
        "title": "Journalist",
        "salary": "₹3–12 LPA",
        "riasec_primary": "A",
        "riasec_secondary": "S",
        "streams": ["arts", "comm"],
        "subject_weights": {
            "history": 0.6,
            "politicalScience": 0.7,
            "geography": 0.4,
        },
        "workstyle_weights": {
            "creative": 0.8,
            "researching": 0.7,
            "helping": 0.5,
        },
        "priority_alignment": ["Social Impact", "Creative Freedom"],
        "sector": "private",
        "cost_level": "low",
        "requires_relocation": True,
        "reason": "Journalism is about finding truth and telling it clearly to the public. Journalists investigate, interview, research, and write — serving as the link between events and the citizens who need to understand them.",
    },

    {
        "title": "Game Designer",
        "salary": "₹6–22 LPA",
        "riasec_primary": "A",
        "riasec_secondary": "I",
        "streams": ["pcm", "pcmb", "arts"],
        "subject_weights": {
            "computerScience": 0.8,
            "mathematics": 0.6,
        },
        "workstyle_weights": {
            "creative": 0.9,
            "building": 0.7,
            "researching": 0.5,
        },
        "priority_alignment": ["Creative Freedom", "Intellectual Challenge"],
        "sector": "private",
        "cost_level": "medium",
        "requires_relocation": True,
        "reason": "Game design combines technical building, creative world-making, and deep understanding of player psychology. Game Designers craft interactive experiences that millions of people choose to spend time in — one of the most creative and technically demanding careers in technology.",
    },

    # ─── Social Primary ────────────────────────────────────────────────────────

    {
        "title": "Teacher / Educator",
        "salary": "₹3–12 LPA",
        "riasec_primary": "S",
        "riasec_secondary": "A",
        "streams": ["pcm", "pcb", "pcmb", "arts", "comm"],
        "subject_weights": {
            "history": 0.5,
            "biology": 0.4,
            "mathematics": 0.4,
            "politicalScience": 0.4,
        },
        "workstyle_weights": {
            "helping": 0.95,
            "creative": 0.5,
            "leading": 0.5,
        },
        "priority_alignment": ["Social Impact", "Work Life Balance", "Job Stability"],
        "sector": "govt",
        "cost_level": "low",
        "requires_relocation": False,
        "reason": "Teaching is one of the most directly impactful careers a person can choose — shaping how young minds understand the world. Educators combine deep subject knowledge with the ability to explain, inspire, and guide students through their most formative years.",
    },

    {
        "title": "Social Worker / NGO Manager",
        "salary": "₹3–15 LPA",
        "riasec_primary": "S",
        "riasec_secondary": "E",
        "streams": ["arts", "comm"],
        "subject_weights": {
            "politicalScience": 0.7,
            "history": 0.5,
            "geography": 0.4,
        },
        "workstyle_weights": {
            "helping": 0.95,
            "leading": 0.6,
            "researching": 0.4,
        },
        "priority_alignment": ["Social Impact", "Work Life Balance"],
        "sector": "govt",
        "cost_level": "low",
        "requires_relocation": True,
        "reason": "Social work is driven by the belief that systemic change and individual support can improve lives. Social workers and NGO managers design programs, advocate for communities, and directly support people navigating poverty, health challenges, and inequality.",
    },

    {
        "title": "HR Manager",
        "salary": "₹6–18 LPA",
        "riasec_primary": "S",
        "riasec_secondary": "E",
        "streams": ["comm", "arts"],
        "subject_weights": {
            "economics": 0.5,
            "politicalScience": 0.4,
            "businessStudies": 0.6,
        },
        "workstyle_weights": {
            "helping": 0.85,
            "leading": 0.7,
            "structured": 0.6,
        },
        "priority_alignment": ["Work Life Balance", "Job Stability", "Social Impact"],
        "sector": "private",
        "cost_level": "medium",
        "requires_relocation": False,
        "reason": "Human Resources is about building and maintaining the environment where people do their best work. HR Managers handle hiring, culture, conflict resolution, and employee development — making them the people who hold organisations together from the inside.",
    },

    {
        "title": "Clinical / Counselling Psychologist",
        "salary": "₹5–18 LPA",
        "riasec_primary": "S",
        "riasec_secondary": "I",
        "streams": ["pcb", "arts"],
        "subject_weights": {
            "biology": 0.6,
            "history": 0.4,
        },
        "workstyle_weights": {
            "helping": 0.95,
            "researching": 0.6,
            "creative": 0.4,
        },
        "priority_alignment": ["Social Impact", "Intellectual Challenge"],
        "sector": "private",
        "cost_level": "medium",
        "requires_relocation": False,
        "reason": "Clinical and counselling psychologists help people understand and manage their mental and emotional lives. It is a career that demands both scientific rigour (evidence-based therapy methods) and deep human empathy — working with some of the most complex challenges people face.",
    },

    # ─── Enterprising Primary ──────────────────────────────────────────────────

    {
        "title": "Management Consultant",
        "salary": "₹10–35 LPA",
        "riasec_primary": "E",
        "riasec_secondary": "I",
        "streams": ["comm", "pcm", "pcmb"],
        "subject_weights": {
            "mathematics": 0.7,
            "economics": 0.85,
            "businessStudies": 0.8,
            "accountancy": 0.5,
        },
        "workstyle_weights": {
            "leading": 0.85,
            "researching": 0.7,
            "structured": 0.6,
        },
        "priority_alignment": ["High Salary", "Intellectual Challenge"],
        "sector": "private",
        "cost_level": "high",
        "requires_relocation": True,
        "reason": "Management consultants solve complex business problems for organisations across industries. They analyse data, identify inefficiencies, and recommend strategic changes — a career that rewards ambitious analytical thinkers who can also communicate and influence.",
    },

    {
        "title": "Investment Banker",
        "salary": "₹12–40 LPA",
        "riasec_primary": "E",
        "riasec_secondary": "C",
        "streams": ["comm", "pcm"],
        "subject_weights": {
            "mathematics": 0.85,
            "economics": 0.9,
            "accountancy": 0.8,
            "businessStudies": 0.7,
        },
        "workstyle_weights": {
            "leading": 0.8,
            "researching": 0.6,
            "structured": 0.7,
        },
        "priority_alignment": ["High Salary", "Intellectual Challenge"],
        "sector": "private",
        "cost_level": "high",
        "requires_relocation": True,
        "reason": "Investment bankers advise companies on raising capital, mergers, and major financial decisions. It is one of the highest-pressure and highest-reward careers in finance — demanding sharp analytical skills, resilience, and the ability to manage complex deals.",
    },

    {
        "title": "Entrepreneur",
        "salary": "Variable",
        "riasec_primary": "E",
        "riasec_secondary": "I",
        "streams": ["pcm", "pcmb", "comm", "arts"],
        "subject_weights": {
            "mathematics": 0.5,
            "economics": 0.6,
            "businessStudies": 0.6,
        },
        "workstyle_weights": {
            "leading": 0.9,
            "building": 0.7,
            "creative": 0.6,
        },
        "priority_alignment": ["Creative Freedom", "High Salary", "Intellectual Challenge"],
        "sector": "entrepreneur",
        "cost_level": "low",
        "requires_relocation": False,
        "reason": "Entrepreneurship is building something from nothing — identifying a problem, assembling a team, and executing relentlessly under uncertainty. It is the career path that rewards the most diverse skill set: vision, execution, resilience, and the ability to lead.",
    },

    {
        "title": "Marketing Manager",
        "salary": "₹7–22 LPA",
        "riasec_primary": "E",
        "riasec_secondary": "A",
        "streams": ["comm", "arts"],
        "subject_weights": {
            "economics": 0.7,
            "businessStudies": 0.8,
            "accountancy": 0.4,
        },
        "workstyle_weights": {
            "leading": 0.8,
            "creative": 0.75,
            "researching": 0.5,
        },
        "priority_alignment": ["Creative Freedom", "High Salary"],
        "sector": "private",
        "cost_level": "medium",
        "requires_relocation": False,
        "reason": "Marketing managers create campaigns and strategies that connect products with people. They combine creative storytelling, data-driven targeting, and business understanding to influence how brands are perceived — and to drive real revenue growth.",
    },

    {
        "title": "IAS / Civil Services Officer",
        "salary": "₹8–20 LPA",
        "riasec_primary": "E",
        "riasec_secondary": "S",
        "streams": ["arts", "comm", "pcm", "pcb", "pcmb"],
        "subject_weights": {
            "history": 0.8,
            "geography": 0.8,
            "politicalScience": 0.85,
            "economics": 0.7,
        },
        "workstyle_weights": {
            "leading": 0.9,
            "helping": 0.7,
            "structured": 0.6,
        },
        "priority_alignment": ["Social Impact", "Job Stability"],
        "sector": "govt",
        "cost_level": "low",
        "requires_relocation": True,
        "reason": "Civil Services officers lead the implementation of government policy at district, state, and national levels. The IAS and allied services offer the rare combination of authority, social impact, and intellectual challenge — solving real problems that affect millions of people.",
    },

    {
        "title": "Lawyer / Legal Advisor",
        "salary": "₹5–30 LPA",
        "riasec_primary": "E",
        "riasec_secondary": "I",
        "streams": ["arts", "comm"],
        "subject_weights": {
            "history": 0.6,
            "politicalScience": 0.85,
            "economics": 0.5,
        },
        "workstyle_weights": {
            "leading": 0.85,
            "researching": 0.7,
            "helping": 0.5,
        },
        "priority_alignment": ["Intellectual Challenge", "High Salary"],
        "sector": "private",
        "cost_level": "medium",
        "requires_relocation": False,
        "reason": "Law is about constructing arguments, navigating complex systems, and advocating for outcomes — whether in a courtroom, a boardroom, or a policy chamber. Lawyers combine deep analytical thinking with persuasive communication to represent and advise clients.",
    },

    # ─── Conventional Primary ──────────────────────────────────────────────────

    {
        "title": "Chartered Accountant",
        "salary": "₹8–25 LPA",
        "riasec_primary": "C",
        "riasec_secondary": "E",
        "streams": ["comm"],
        "subject_weights": {
            "accountancy": 0.95,
            "mathematics": 0.85,
            "economics": 0.7,
            "businessStudies": 0.6,
        },
        "workstyle_weights": {
            "structured": 0.9,
            "researching": 0.5,
            "leading": 0.4,
        },
        "priority_alignment": ["High Salary", "Job Stability"],
        "sector": "private",
        "cost_level": "low",
        "requires_relocation": False,
        "reason": "Chartered Accountants are the financial backbone of organisations — auditing accounts, managing tax compliance, and providing strategic financial advice. It is one of India's most respected and financially rewarding professional qualifications.",
    },

    {
        "title": "Financial Analyst",
        "salary": "₹7–22 LPA",
        "riasec_primary": "C",
        "riasec_secondary": "I",
        "streams": ["comm", "pcm"],
        "subject_weights": {
            "mathematics": 0.9,
            "accountancy": 0.8,
            "economics": 0.85,
        },
        "workstyle_weights": {
            "structured": 0.85,
            "researching": 0.7,
            "leading": 0.3,
        },
        "priority_alignment": ["High Salary", "Intellectual Challenge"],
        "sector": "private",
        "cost_level": "medium",
        "requires_relocation": False,
        "reason": "Financial analysts evaluate investment opportunities, model company performance, and advise on financial strategy. This career rewards precision, numerical fluency, and the ability to synthesise complex financial data into clear recommendations.",
    },

    {
        "title": "Operations Manager",
        "salary": "₹8–20 LPA",
        "riasec_primary": "C",
        "riasec_secondary": "E",
        "streams": ["comm", "pcm"],
        "subject_weights": {
            "mathematics": 0.7,
            "businessStudies": 0.8,
            "economics": 0.6,
        },
        "workstyle_weights": {
            "structured": 0.85,
            "leading": 0.75,
            "building": 0.4,
        },
        "priority_alignment": ["Job Stability", "High Salary"],
        "sector": "private",
        "cost_level": "medium",
        "requires_relocation": False,
        "reason": "Operations managers keep organisations running efficiently — coordinating logistics, managing teams, and optimising processes. It is a career that combines systematic thinking with leadership, and rewards people who find satisfaction in making complex systems work smoothly.",
    },

    {
        "title": "Supply Chain Manager",
        "salary": "₹7–22 LPA",
        "riasec_primary": "C",
        "riasec_secondary": "R",
        "streams": ["comm", "pcm"],
        "subject_weights": {
            "mathematics": 0.75,
            "businessStudies": 0.7,
            "economics": 0.65,
        },
        "workstyle_weights": {
            "structured": 0.85,
            "building": 0.5,
            "researching": 0.5,
        },
        "priority_alignment": ["Job Stability", "Intellectual Challenge"],
        "sector": "private",
        "cost_level": "medium",
        "requires_relocation": True,
        "reason": "Supply chain managers coordinate the flow of goods from supplier to customer — balancing cost, speed, and reliability across complex global networks. This is a career for systematic thinkers who enjoy optimising large, moving systems.",
    },

    {
        "title": "Quality Assurance Analyst",
        "salary": "₹5–15 LPA",
        "riasec_primary": "C",
        "riasec_secondary": "R",
        "streams": ["pcm", "pcmb", "comm"],
        "subject_weights": {
            "mathematics": 0.7,
            "computerScience": 0.6,
            "chemistry": 0.4,
        },
        "workstyle_weights": {
            "structured": 0.9,
            "building": 0.5,
            "researching": 0.5,
        },
        "priority_alignment": ["Job Stability", "Intellectual Challenge"],
        "sector": "private",
        "cost_level": "medium",
        "requires_relocation": False,
        "reason": "QA Analysts ensure that software, products, and processes meet defined quality standards — finding errors before they reach end users. This career rewards methodical thinking, attention to detail, and a systematic approach to testing and verification.",
    },

    {
        "title": "Bank Manager / Finance Officer",
        "salary": "₹8–18 LPA",
        "riasec_primary": "C",
        "riasec_secondary": "S",
        "streams": ["comm"],
        "subject_weights": {
            "accountancy": 0.8,
            "economics": 0.8,
            "mathematics": 0.7,
            "businessStudies": 0.6,
        },
        "workstyle_weights": {
            "structured": 0.85,
            "helping": 0.6,
            "leading": 0.5,
        },
        "priority_alignment": ["Job Stability", "High Salary"],
        "sector": "govt",
        "cost_level": "low",
        "requires_relocation": True,
        "reason": "Banking and finance officers manage accounts, evaluate loan applications, and serve as the financial hub for individuals and businesses. Government bank roles in India offer strong job security, structured growth, and wide social reach.",
    },
]
