"""
career_catalog.py
Flat list of careers used exclusively by the unified scoring engine.
Each entry has full metadata for all 5 scoring components.
DO NOT modify aptitude-backend/career_mapping.py — that is unchanged.
"""

CAREER_CATALOG = [

    # ─── Investigative Primary ─────────────────────────────────────────────────

    {
        "title": "Data Scientist",
        "salary": "₹8–25 LPA",
        "riasec_primary": "I",
        "riasec_secondary": "R",
        "streams": ["pcm", "pcmb"],
        "subject_weights": {
            "mathematics": 0.9,
            "computerScience": 0.85,
            "physics": 0.5,
            "statistics": 0.7,
        },
        "workstyle_weights": {
            "researching": 0.9,
            "building": 0.4,
            "structured": 0.5,
        },
        "priority_alignment": ["Intellectual Challenge", "High Salary"],
        "sector": "private",
        "cost_level": "medium",
        "requires_relocation": False,
        "reason": "Your analytical nature and curiosity are exactly what data science rewards. Data Scientists spend their days finding patterns in complex datasets and building models that power real decisions — the kind of deep, focused problem-solving your profile points toward.",
    },

    {
        "title": "Software Engineer",
        "salary": "₹7–30 LPA",
        "riasec_primary": "I",
        "riasec_secondary": "R",
        "streams": ["pcm", "pcmb"],
        "subject_weights": {
            "mathematics": 0.85,
            "computerScience": 0.95,
            "physics": 0.4,
        },
        "workstyle_weights": {
            "researching": 0.6,
            "building": 0.8,
            "structured": 0.6,
        },
        "priority_alignment": ["High Salary", "Intellectual Challenge", "Work Life Balance"],
        "sector": "private",
        "cost_level": "medium",
        "requires_relocation": False,
        "reason": "Logical problem solving is the daily currency of software engineering. Engineers design systems, debug complex issues, and build tools that millions of people use — a career that rewards the kind of structured analytical thinking your profile shows.",
    },

    {
        "title": "Research Scientist",
        "salary": "₹6–18 LPA",
        "riasec_primary": "I",
        "riasec_secondary": "I",
        "streams": ["pcm", "pcb", "pcmb"],
        "subject_weights": {
            "physics": 0.8,
            "chemistry": 0.8,
            "biology": 0.7,
            "mathematics": 0.7,
        },
        "workstyle_weights": {
            "researching": 0.95,
            "building": 0.3,
            "structured": 0.5,
        },
        "priority_alignment": ["Intellectual Challenge", "Social Impact"],
        "sector": "study",
        "cost_level": "low",
        "requires_relocation": True,
        "reason": "Your curiosity and drive to understand how things work are the defining traits of a research scientist. Research Scientists spend years exploring unknowns — running experiments, publishing findings, and pushing the boundaries of human knowledge.",
    },

    {
        "title": "Data Analyst",
        "salary": "₹5–18 LPA",
        "riasec_primary": "I",
        "riasec_secondary": "C",
        "streams": ["pcm", "pcmb", "comm"],
        "subject_weights": {
            "mathematics": 0.85,
            "computerScience": 0.7,
            "economics": 0.6,
            "accountancy": 0.4,
        },
        "workstyle_weights": {
            "researching": 0.8,
            "structured": 0.7,
            "building": 0.3,
        },
        "priority_alignment": ["Intellectual Challenge", "Job Stability"],
        "sector": "private",
        "cost_level": "medium",
        "requires_relocation": False,
        "reason": "Turning raw numbers into actionable business insights is the core of data analysis. Data Analysts work at the intersection of logic and communication — finding the story inside data that organisations use to make better decisions.",
    },

    {
        "title": "Biomedical Engineer",
        "salary": "₹6–20 LPA",
        "riasec_primary": "I",
        "riasec_secondary": "R",
        "streams": ["pcb", "pcmb"],
        "subject_weights": {
            "biology": 0.85,
            "chemistry": 0.75,
            "physics": 0.7,
            "mathematics": 0.6,
        },
        "workstyle_weights": {
            "researching": 0.8,
            "building": 0.7,
            "structured": 0.5,
        },
        "priority_alignment": ["Social Impact", "Intellectual Challenge"],
        "sector": "private",
        "cost_level": "medium",
        "requires_relocation": False,
        "reason": "Combining engineering principles with medical science to solve real healthcare problems is the heart of biomedical engineering. Biomedical Engineers design medical devices, prosthetics, and diagnostic tools that improve and save lives.",
    },

    {
        "title": "Environmental Scientist",
        "salary": "₹5–15 LPA",
        "riasec_primary": "I",
        "riasec_secondary": "R",
        "streams": ["pcb", "pcmb"],
        "subject_weights": {
            "biology": 0.85,
            "chemistry": 0.8,
            "geography": 0.6,
            "physics": 0.4,
        },
        "workstyle_weights": {
            "researching": 0.85,
            "building": 0.4,
            "helping": 0.5,
        },
        "priority_alignment": ["Social Impact", "Intellectual Challenge"],
        "sector": "govt",
        "cost_level": "low",
        "requires_relocation": True,
        "reason": "Studying how ecosystems function and how human activity affects them is at the core of environmental science. Environmental Scientists gather field data, analyse pollution and climate patterns, and inform the policies that protect our planet.",
    },

    {
        "title": "Psychologist",
        "salary": "₹4–18 LPA",
        "riasec_primary": "I",
        "riasec_secondary": "S",
        "streams": ["pcb", "arts"],
        "subject_weights": {
            "biology": 0.6,
            "history": 0.5,
            "politicalScience": 0.4,
        },
        "workstyle_weights": {
            "researching": 0.75,
            "helping": 0.85,
            "creative": 0.4,
        },
        "priority_alignment": ["Social Impact", "Intellectual Challenge"],
        "sector": "private",
        "cost_level": "medium",
        "requires_relocation": False,
        "reason": "Understanding how the mind works and helping people navigate mental and emotional challenges defines the psychologist's work. Psychologists apply evidence-based methods to assess, diagnose, and support people through clinical, educational, or research settings.",
    },

    {
        "title": "UX Researcher",
        "salary": "₹7–22 LPA",
        "riasec_primary": "I",
        "riasec_secondary": "A",
        "streams": ["pcm", "pcmb", "arts", "comm"],
        "subject_weights": {
            "computerScience": 0.6,
            "mathematics": 0.5,
            "history": 0.3,
        },
        "workstyle_weights": {
            "researching": 0.85,
            "creative": 0.7,
            "helping": 0.6,
        },
        "priority_alignment": ["Intellectual Challenge", "Creative Freedom"],
        "sector": "private",
        "cost_level": "medium",
        "requires_relocation": False,
        "reason": "UX Research sits at the intersection of analytical thinking and human empathy. UX Researchers design studies, conduct user interviews, and synthesise findings to make digital products intuitive — combining rigorous method with creative insight.",
    },

    # ─── Realistic Primary ─────────────────────────────────────────────────────

    {
        "title": "Mechanical Engineer",
        "salary": "₹5–18 LPA",
        "riasec_primary": "R",
        "riasec_secondary": "I",
        "streams": ["pcm", "pcmb"],
        "subject_weights": {
            "physics": 0.9,
            "mathematics": 0.85,
            "chemistry": 0.5,
        },
        "workstyle_weights": {
            "building": 0.9,
            "researching": 0.5,
            "structured": 0.6,
        },
        "priority_alignment": ["Job Stability", "Intellectual Challenge"],
        "sector": "private",
        "cost_level": "medium",
        "requires_relocation": False,
        "reason": "Designing, analysing, and manufacturing physical systems is what mechanical engineers do every day. This career rewards practical intelligence and the ability to turn abstract physics into machines, engines, and systems that actually work in the real world.",
    },

    {
        "title": "Civil Engineer",
        "salary": "₹5–16 LPA",
        "riasec_primary": "R",
        "riasec_secondary": "I",
        "streams": ["pcm", "pcmb"],
        "subject_weights": {
            "mathematics": 0.85,
            "physics": 0.8,
            "geography": 0.4,
        },
        "workstyle_weights": {
            "building": 0.9,
            "structured": 0.7,
            "researching": 0.4,
        },
        "priority_alignment": ["Job Stability", "Social Impact"],
        "sector": "govt",
        "cost_level": "low",
        "requires_relocation": True,
        "reason": "Bridges, dams, roads, and buildings — civil engineers design and oversee the infrastructure that holds society together. This career combines spatial reasoning, mathematics, and hands-on site management to create lasting physical structures.",
    },

    {
        "title": "Electrical Engineer",
        "salary": "₹4–20 LPA",
        "riasec_primary": "R",
        "riasec_secondary": "I",
        "streams": ["pcm", "pcmb"],
        "subject_weights": {
            "physics": 0.9,
            "mathematics": 0.85,
            "computerScience": 0.5,
        },
        "workstyle_weights": {
            "building": 0.85,
            "researching": 0.5,
            "structured": 0.6,
        },
        "priority_alignment": ["Job Stability", "Intellectual Challenge"],
        "sector": "private",
        "cost_level": "medium",
        "requires_relocation": False,
        "reason": "Designing electrical systems, circuits, and power infrastructure that keep the modern world running is the electrical engineer's core work. From power grids to embedded electronics, this field rewards technical precision and hands-on problem solving.",
    },

    {
        "title": "Architect",
        "salary": "₹5–20 LPA",
        "riasec_primary": "R",
        "riasec_secondary": "A",
        "streams": ["pcm", "pcmb"],
        "subject_weights": {
            "mathematics": 0.8,
            "physics": 0.6,
        },
        "workstyle_weights": {
            "building": 0.8,
            "creative": 0.85,
            "structured": 0.5,
        },
        "priority_alignment": ["Creative Freedom", "Intellectual Challenge"],
        "sector": "private",
        "cost_level": "high",
        "requires_relocation": False,
        "reason": "Architecture is where design meets engineering — creating spaces that are both structurally sound and aesthetically powerful. Architects design buildings from initial concept through construction, balancing artistic vision with practical constraints.",
    },

    {
        "title": "Doctor (MBBS)",
        "salary": "₹6–25 LPA",
        "riasec_primary": "R",
        "riasec_secondary": "S",
        "streams": ["pcb", "pcmb"],
        "subject_weights": {
            "biology": 0.95,
            "chemistry": 0.9,
            "physics": 0.5,
        },
        "workstyle_weights": {
            "helping": 0.9,
            "building": 0.5,
            "researching": 0.5,
        },
        "priority_alignment": ["Social Impact", "Job Stability", "High Salary"],
        "sector": "private",
        "cost_level": "medium",
        "requires_relocation": False,
        "reason": "Medicine combines deep scientific knowledge with direct human impact. Doctors diagnose illness, treat patients, and make critical decisions daily — a career for those who want rigorous intellectual challenge and the profound satisfaction of helping people heal.",
    },

    {
        "title": "Physiotherapist",
        "salary": "₹4–12 LPA",
        "riasec_primary": "R",
        "riasec_secondary": "S",
        "streams": ["pcb", "pcmb"],
        "subject_weights": {
            "biology": 0.9,
            "chemistry": 0.6,
            "physics": 0.5,
        },
        "workstyle_weights": {
            "helping": 0.9,
            "building": 0.6,
            "structured": 0.5,
        },
        "priority_alignment": ["Social Impact", "Work Life Balance"],
        "sector": "private",
        "cost_level": "medium",
        "requires_relocation": False,
        "reason": "Physiotherapists help patients recover movement and manage pain using evidence-based physical techniques. It is a career that combines biological knowledge with hands-on therapeutic skill and the genuine satisfaction of watching people regain their mobility.",
    },

    # ─── Artistic Primary ──────────────────────────────────────────────────────

    {
        "title": "UI/UX Designer",
        "salary": "₹6–22 LPA",
        "riasec_primary": "A",
        "riasec_secondary": "I",
        "streams": ["pcm", "pcmb", "arts", "comm"],
        "subject_weights": {
            "computerScience": 0.7,
            "mathematics": 0.4,
        },
        "workstyle_weights": {
            "creative": 0.9,
            "researching": 0.6,
            "building": 0.5,
        },
        "priority_alignment": ["Creative Freedom", "Intellectual Challenge", "High Salary"],
        "sector": "private",
        "cost_level": "medium",
        "requires_relocation": False,
        "reason": "UI/UX Design is where aesthetic sensibility meets user psychology. Designers craft the visual and interactive experience of apps and websites — solving real problems with creative solutions that make digital products feel intuitive and beautiful.",
    },

    {
        "title": "Graphic Designer",
        "salary": "₹4–15 LPA",
        "riasec_primary": "A",
        "riasec_secondary": "E",
        "streams": ["arts", "pcm", "comm"],
        "subject_weights": {
            "computerScience": 0.4,
        },
        "workstyle_weights": {
            "creative": 0.95,
            "building": 0.5,
            "leading": 0.3,
        },
        "priority_alignment": ["Creative Freedom", "Work Life Balance"],
        "sector": "private",
        "cost_level": "low",
        "requires_relocation": False,
        "reason": "Graphic designers communicate ideas visually — through logos, layouts, illustrations, and brand identities. This is a career for people who think in images, have a strong sense of composition and colour, and want their creativity to drive their work.",
    },

    {
        "title": "Film Director / Content Creator",
        "salary": "₹6–30 LPA",
        "riasec_primary": "A",
        "riasec_secondary": "E",
        "streams": ["arts", "comm"],
        "subject_weights": {
            "history": 0.4,
            "politicalScience": 0.3,
        },
        "workstyle_weights": {
            "creative": 0.95,
            "leading": 0.7,
            "helping": 0.4,
        },
        "priority_alignment": ["Creative Freedom", "Social Impact"],
        "sector": "entrepreneur",
        "cost_level": "low",
        "requires_relocation": False,
        "reason": "Film direction and content creation are about bringing stories and ideas to life for an audience. Directors and creators lead teams, make hundreds of decisions every day, and translate creative vision into compelling visual narratives.",
    },

    {
        "title": "Journalist",
        "salary": "₹3–12 LPA",
        "riasec_primary": "A",
        "riasec_secondary": "S",
        "streams": ["arts", "comm"],
        "subject_weights": {
            "history": 0.6,
            "politicalScience": 0.7,
            "geography": 0.4,
        },
        "workstyle_weights": {
            "creative": 0.8,
            "researching": 0.7,
            "helping": 0.5,
        },
        "priority_alignment": ["Social Impact", "Creative Freedom"],
        "sector": "private",
        "cost_level": "low",
        "requires_relocation": True,
        "reason": "Journalism is about finding truth and telling it clearly to the public. Journalists investigate, interview, research, and write — serving as the link between events and the citizens who need to understand them.",
    },

    {
        "title": "Game Designer",
        "salary": "₹6–22 LPA",
        "riasec_primary": "A",
        "riasec_secondary": "I",
        "streams": ["pcm", "pcmb", "arts"],
        "subject_weights": {
            "computerScience": 0.8,
            "mathematics": 0.6,
        },
        "workstyle_weights": {
            "creative": 0.9,
            "building": 0.7,
            "researching": 0.5,
        },
        "priority_alignment": ["Creative Freedom", "Intellectual Challenge"],
        "sector": "private",
        "cost_level": "medium",
        "requires_relocation": True,
        "reason": "Game design combines technical building, creative world-making, and deep understanding of player psychology. Game Designers craft interactive experiences that millions of people choose to spend time in — one of the most creative and technically demanding careers in technology.",
    },

    # ─── Social Primary ────────────────────────────────────────────────────────

    {
        "title": "Teacher / Educator",
        "salary": "₹3–12 LPA",
        "riasec_primary": "S",
        "riasec_secondary": "A",
        "streams": ["pcm", "pcb", "pcmb", "arts", "comm"],
        "subject_weights": {
            "history": 0.5,
            "biology": 0.4,
            "mathematics": 0.4,
            "politicalScience": 0.4,
        },
        "workstyle_weights": {
            "helping": 0.95,
            "creative": 0.5,
            "leading": 0.5,
        },
        "priority_alignment": ["Social Impact", "Work Life Balance", "Job Stability"],
        "sector": "govt",
        "cost_level": "low",
        "requires_relocation": False,
        "reason": "Teaching is one of the most directly impactful careers a person can choose — shaping how young minds understand the world. Educators combine deep subject knowledge with the ability to explain, inspire, and guide students through their most formative years.",
    },

    {
        "title": "Social Worker / NGO Manager",
        "salary": "₹3–15 LPA",
        "riasec_primary": "S",
        "riasec_secondary": "E",
        "streams": ["arts", "comm"],
        "subject_weights": {
            "politicalScience": 0.7,
            "history": 0.5,
            "geography": 0.4,
        },
        "workstyle_weights": {
            "helping": 0.95,
            "leading": 0.6,
            "researching": 0.4,
        },
        "priority_alignment": ["Social Impact", "Work Life Balance"],
        "sector": "govt",
        "cost_level": "low",
        "requires_relocation": True,
        "reason": "Social work is driven by the belief that systemic change and individual support can improve lives. Social workers and NGO managers design programs, advocate for communities, and directly support people navigating poverty, health challenges, and inequality.",
    },

    {
        "title": "HR Manager",
        "salary": "₹6–18 LPA",
        "riasec_primary": "S",
        "riasec_secondary": "E",
        "streams": ["comm", "arts"],
        "subject_weights": {
            "economics": 0.5,
            "politicalScience": 0.4,
            "businessStudies": 0.6,
        },
        "workstyle_weights": {
            "helping": 0.85,
            "leading": 0.7,
            "structured": 0.6,
        },
        "priority_alignment": ["Work Life Balance", "Job Stability", "Social Impact"],
        "sector": "private",
        "cost_level": "medium",
        "requires_relocation": False,
        "reason": "Human Resources is about building and maintaining the environment where people do their best work. HR Managers handle hiring, culture, conflict resolution, and employee development — making them the people who hold organisations together from the inside.",
    },

    {
        "title": "Clinical / Counselling Psychologist",
        "salary": "₹5–18 LPA",
        "riasec_primary": "S",
        "riasec_secondary": "I",
        "streams": ["pcb", "arts"],
        "subject_weights": {
            "biology": 0.6,
            "history": 0.4,
        },
        "workstyle_weights": {
            "helping": 0.95,
            "researching": 0.6,
            "creative": 0.4,
        },
        "priority_alignment": ["Social Impact", "Intellectual Challenge"],
        "sector": "private",
        "cost_level": "medium",
        "requires_relocation": False,
        "reason": "Clinical and counselling psychologists help people understand and manage their mental and emotional lives. It is a career that demands both scientific rigour (evidence-based therapy methods) and deep human empathy — working with some of the most complex challenges people face.",
    },

    # ─── Enterprising Primary ──────────────────────────────────────────────────

    {
        "title": "Management Consultant",
        "salary": "₹10–35 LPA",
        "riasec_primary": "E",
        "riasec_secondary": "I",
        "streams": ["comm", "pcm", "pcmb"],
        "subject_weights": {
            "mathematics": 0.7,
            "economics": 0.85,
            "businessStudies": 0.8,
            "accountancy": 0.5,
        },
        "workstyle_weights": {
            "leading": 0.85,
            "researching": 0.7,
            "structured": 0.6,
        },
        "priority_alignment": ["High Salary", "Intellectual Challenge"],
        "sector": "private",
        "cost_level": "high",
        "requires_relocation": True,
        "reason": "Management consultants solve complex business problems for organisations across industries. They analyse data, identify inefficiencies, and recommend strategic changes — a career that rewards ambitious analytical thinkers who can also communicate and influence.",
    },

    {
        "title": "Investment Banker",
        "salary": "₹12–40 LPA",
        "riasec_primary": "E",
        "riasec_secondary": "C",
        "streams": ["comm", "pcm"],
        "subject_weights": {
            "mathematics": 0.85,
            "economics": 0.9,
            "accountancy": 0.8,
            "businessStudies": 0.7,
        },
        "workstyle_weights": {
            "leading": 0.8,
            "researching": 0.6,
            "structured": 0.7,
        },
        "priority_alignment": ["High Salary", "Intellectual Challenge"],
        "sector": "private",
        "cost_level": "high",
        "requires_relocation": True,
        "reason": "Investment bankers advise companies on raising capital, mergers, and major financial decisions. It is one of the highest-pressure and highest-reward careers in finance — demanding sharp analytical skills, resilience, and the ability to manage complex deals.",
    },

    {
        "title": "Entrepreneur",
        "salary": "Variable",
        "riasec_primary": "E",
        "riasec_secondary": "I",
        "streams": ["pcm", "pcmb", "comm", "arts"],
        "subject_weights": {
            "mathematics": 0.5,
            "economics": 0.6,
            "businessStudies": 0.6,
        },
        "workstyle_weights": {
            "leading": 0.9,
            "building": 0.7,
            "creative": 0.6,
        },
        "priority_alignment": ["Creative Freedom", "High Salary", "Intellectual Challenge"],
        "sector": "entrepreneur",
        "cost_level": "low",
        "requires_relocation": False,
        "reason": "Entrepreneurship is building something from nothing — identifying a problem, assembling a team, and executing relentlessly under uncertainty. It is the career path that rewards the most diverse skill set: vision, execution, resilience, and the ability to lead.",
    },

    {
        "title": "Marketing Manager",
        "salary": "₹7–22 LPA",
        "riasec_primary": "E",
        "riasec_secondary": "A",
        "streams": ["comm", "arts"],
        "subject_weights": {
            "economics": 0.7,
            "businessStudies": 0.8,
            "accountancy": 0.4,
        },
        "workstyle_weights": {
            "leading": 0.8,
            "creative": 0.75,
            "researching": 0.5,
        },
        "priority_alignment": ["Creative Freedom", "High Salary"],
        "sector": "private",
        "cost_level": "medium",
        "requires_relocation": False,
        "reason": "Marketing managers create campaigns and strategies that connect products with people. They combine creative storytelling, data-driven targeting, and business understanding to influence how brands are perceived — and to drive real revenue growth.",
    },

    {
        "title": "IAS / Civil Services Officer",
        "salary": "₹8–20 LPA",
        "riasec_primary": "E",
        "riasec_secondary": "S",
        "streams": ["arts", "comm", "pcm", "pcb", "pcmb"],
        "subject_weights": {
            "history": 0.8,
            "geography": 0.8,
            "politicalScience": 0.85,
            "economics": 0.7,
        },
        "workstyle_weights": {
            "leading": 0.9,
            "helping": 0.7,
            "structured": 0.6,
        },
        "priority_alignment": ["Social Impact", "Job Stability"],
        "sector": "govt",
        "cost_level": "low",
        "requires_relocation": True,
        "reason": "Civil Services officers lead the implementation of government policy at district, state, and national levels. The IAS and allied services offer the rare combination of authority, social impact, and intellectual challenge — solving real problems that affect millions of people.",
    },

    {
        "title": "Lawyer / Legal Advisor",
        "salary": "₹5–30 LPA",
        "riasec_primary": "E",
        "riasec_secondary": "I",
        "streams": ["arts", "comm"],
        "subject_weights": {
            "history": 0.6,
            "politicalScience": 0.85,
            "economics": 0.5,
        },
        "workstyle_weights": {
            "leading": 0.85,
            "researching": 0.7,
            "helping": 0.5,
        },
        "priority_alignment": ["Intellectual Challenge", "High Salary"],
        "sector": "private",
        "cost_level": "medium",
        "requires_relocation": False,
        "reason": "Law is about constructing arguments, navigating complex systems, and advocating for outcomes — whether in a courtroom, a boardroom, or a policy chamber. Lawyers combine deep analytical thinking with persuasive communication to represent and advise clients.",
    },

    # ─── Conventional Primary ──────────────────────────────────────────────────

    {
        "title": "Chartered Accountant",
        "salary": "₹8–25 LPA",
        "riasec_primary": "C",
        "riasec_secondary": "E",
        "streams": ["comm"],
        "subject_weights": {
            "accountancy": 0.95,
            "mathematics": 0.85,
            "economics": 0.7,
            "businessStudies": 0.6,
        },
        "workstyle_weights": {
            "structured": 0.9,
            "researching": 0.5,
            "leading": 0.4,
        },
        "priority_alignment": ["High Salary", "Job Stability"],
        "sector": "private",
        "cost_level": "low",
        "requires_relocation": False,
        "reason": "Chartered Accountants are the financial backbone of organisations — auditing accounts, managing tax compliance, and providing strategic financial advice. It is one of India's most respected and financially rewarding professional qualifications.",
    },

    {
        "title": "Financial Analyst",
        "salary": "₹7–22 LPA",
        "riasec_primary": "C",
        "riasec_secondary": "I",
        "streams": ["comm", "pcm"],
        "subject_weights": {
            "mathematics": 0.9,
            "accountancy": 0.8,
            "economics": 0.85,
        },
        "workstyle_weights": {
            "structured": 0.85,
            "researching": 0.7,
            "leading": 0.3,
        },
        "priority_alignment": ["High Salary", "Intellectual Challenge"],
        "sector": "private",
        "cost_level": "medium",
        "requires_relocation": False,
        "reason": "Financial analysts evaluate investment opportunities, model company performance, and advise on financial strategy. This career rewards precision, numerical fluency, and the ability to synthesise complex financial data into clear recommendations.",
    },

    {
        "title": "Operations Manager",
        "salary": "₹8–20 LPA",
        "riasec_primary": "C",
        "riasec_secondary": "E",
        "streams": ["comm", "pcm"],
        "subject_weights": {
            "mathematics": 0.7,
            "businessStudies": 0.8,
            "economics": 0.6,
        },
        "workstyle_weights": {
            "structured": 0.85,
            "leading": 0.75,
            "building": 0.4,
        },
        "priority_alignment": ["Job Stability", "High Salary"],
        "sector": "private",
        "cost_level": "medium",
        "requires_relocation": False,
        "reason": "Operations managers keep organisations running efficiently — coordinating logistics, managing teams, and optimising processes. It is a career that combines systematic thinking with leadership, and rewards people who find satisfaction in making complex systems work smoothly.",
    },

    {
        "title": "Supply Chain Manager",
        "salary": "₹7–22 LPA",
        "riasec_primary": "C",
        "riasec_secondary": "R",
        "streams": ["comm", "pcm"],
        "subject_weights": {
            "mathematics": 0.75,
            "businessStudies": 0.7,
            "economics": 0.65,
        },
        "workstyle_weights": {
            "structured": 0.85,
            "building": 0.5,
            "researching": 0.5,
        },
        "priority_alignment": ["Job Stability", "Intellectual Challenge"],
        "sector": "private",
        "cost_level": "medium",
        "requires_relocation": True,
        "reason": "Supply chain managers coordinate the flow of goods from supplier to customer — balancing cost, speed, and reliability across complex global networks. This is a career for systematic thinkers who enjoy optimising large, moving systems.",
    },

    {
        "title": "Quality Assurance Analyst",
        "salary": "₹5–15 LPA",
        "riasec_primary": "C",
        "riasec_secondary": "R",
        "streams": ["pcm", "pcmb", "comm"],
        "subject_weights": {
            "mathematics": 0.7,
            "computerScience": 0.6,
            "chemistry": 0.4,
        },
        "workstyle_weights": {
            "structured": 0.9,
            "building": 0.5,
            "researching": 0.5,
        },
        "priority_alignment": ["Job Stability", "Intellectual Challenge"],
        "sector": "private",
        "cost_level": "medium",
        "requires_relocation": False,
        "reason": "QA Analysts ensure that software, products, and processes meet defined quality standards — finding errors before they reach end users. This career rewards methodical thinking, attention to detail, and a systematic approach to testing and verification.",
    },

    {
        "title": "Bank Manager / Finance Officer",
        "salary": "₹8–18 LPA",
        "riasec_primary": "C",
        "riasec_secondary": "S",
        "streams": ["comm"],
        "subject_weights": {
            "accountancy": 0.8,
            "economics": 0.8,
            "mathematics": 0.7,
            "businessStudies": 0.6,
        },
        "workstyle_weights": {
            "structured": 0.85,
            "helping": 0.6,
            "leading": 0.5,
        },
        "priority_alignment": ["Job Stability", "High Salary"],
        "sector": "govt",
        "cost_level": "low",
        "requires_relocation": True,
        "reason": "Banking and finance officers manage accounts, evaluate loan applications, and serve as the financial hub for individuals and businesses. Government bank roles in India offer strong job security, structured growth, and wide social reach.",
    },

    # ─── Additional Careers (Batch 2) ─────────────────────────────────────────

    {
        "title": "AI / Machine Learning Engineer",
        "salary": "₹8–30 LPA",
        "riasec_primary": "I",
        "riasec_secondary": "R",
        "streams": ["pcm"],
        "subject_weights": {
            "mathematics": 0.95,
            "computerScience": 0.95,
            "physics": 0.5,
        },
        "workstyle_weights": {
            "researching": 0.9,
            "building": 0.85,
            "structured": 0.5,
            "creative": 0.4,
        },
        "priority_alignment": ["High Salary", "Intellectual Challenge"],
        "sector": "private",
        "cost_level": "medium",
        "requires_relocation": False,
        "reason": "AI/ML Engineers design intelligent systems that learn from data — from recommendation engines to self-driving algorithms. If you enjoy mathematics, coding, and pushing the boundaries of what machines can do, this career channels that curiosity into one of the fastest-growing fields in technology.",
    },

    {
        "title": "Cybersecurity Analyst",
        "salary": "₹6–20 LPA",
        "riasec_primary": "I",
        "riasec_secondary": "C",
        "streams": ["pcm"],
        "subject_weights": {
            "computerScience": 0.95,
            "mathematics": 0.7,
            "physics": 0.3,
        },
        "workstyle_weights": {
            "researching": 0.85,
            "structured": 0.8,
            "building": 0.4,
        },
        "priority_alignment": ["Job Stability", "Intellectual Challenge"],
        "sector": "private",
        "cost_level": "medium",
        "requires_relocation": False,
        "reason": "Cybersecurity Analysts act as digital guardians, detecting threats and fortifying systems against increasingly sophisticated attacks. This career suits methodical thinkers who enjoy investigative problem-solving and want a role where demand consistently outstrips supply.",
    },

    {
        "title": "Cloud Architect",
        "salary": "₹7–25 LPA",
        "riasec_primary": "R",
        "riasec_secondary": "I",
        "streams": ["pcm"],
        "subject_weights": {
            "computerScience": 0.95,
            "mathematics": 0.6,
            "physics": 0.3,
        },
        "workstyle_weights": {
            "building": 0.9,
            "structured": 0.7,
            "researching": 0.5,
            "leading": 0.4,
        },
        "priority_alignment": ["High Salary", "Job Stability"],
        "sector": "private",
        "cost_level": "medium",
        "requires_relocation": False,
        "reason": "Cloud Architects design the large-scale infrastructure that powers modern applications — selecting services, ensuring scalability, and keeping costs under control. If you like building robust, well-engineered systems and enjoy staying current with rapidly evolving platforms, this career offers both strong pay and creative engineering challenges.",
    },

    {
        "title": "Robotics Engineer",
        "salary": "₹6–22 LPA",
        "riasec_primary": "R",
        "riasec_secondary": "I",
        "streams": ["pcm"],
        "subject_weights": {
            "mathematics": 0.85,
            "physics": 0.9,
            "computerScience": 0.8,
        },
        "workstyle_weights": {
            "building": 0.95,
            "researching": 0.7,
            "fieldwork": 0.4,
            "creative": 0.3,
        },
        "priority_alignment": ["Intellectual Challenge", "Creativity"],
        "sector": "private",
        "cost_level": "high",
        "requires_relocation": True,
        "reason": "Robotics Engineers bring machines to life — designing, programming, and testing robots for manufacturing, healthcare, and exploration. This career is ideal for hands-on builders who love integrating mechanical design, electronics, and software into tangible working systems.",
    },

    {
        "title": "Aerospace Engineer",
        "salary": "₹7–24 LPA",
        "riasec_primary": "R",
        "riasec_secondary": "I",
        "streams": ["pcm"],
        "subject_weights": {
            "physics": 0.95,
            "mathematics": 0.9,
            "computerScience": 0.5,
            "chemistry": 0.3,
        },
        "workstyle_weights": {
            "building": 0.85,
            "researching": 0.8,
            "structured": 0.6,
            "fieldwork": 0.3,
        },
        "priority_alignment": ["Intellectual Challenge", "High Salary"],
        "sector": "private",
        "cost_level": "high",
        "requires_relocation": True,
        "reason": "Aerospace Engineers design aircraft, spacecraft, and satellite systems — tackling some of humanity's most complex engineering challenges. If physics and mathematics excite you and you dream of contributing to aviation or space exploration, this career puts that passion to work.",
    },

    {
        "title": "Quantum Computing Scientist",
        "salary": "₹10–35 LPA",
        "riasec_primary": "I",
        "riasec_secondary": "R",
        "streams": ["pcm"],
        "subject_weights": {
            "physics": 0.95,
            "mathematics": 0.95,
            "computerScience": 0.7,
        },
        "workstyle_weights": {
            "researching": 0.95,
            "building": 0.4,
            "structured": 0.3,
            "creative": 0.3,
        },
        "priority_alignment": ["Intellectual Challenge", "High Salary"],
        "sector": "study",
        "cost_level": "high",
        "requires_relocation": True,
        "reason": "Quantum Computing Scientists work at the frontier of physics and computer science, developing algorithms that exploit quantum mechanics to solve previously intractable problems. This deeply research-oriented career is perfect for someone who thrives on abstract theory, advanced mathematics, and the thrill of pioneering new science.",
    },

    {
        "title": "VLSI Design / Semiconductor Engineer",
        "salary": "₹7–25 LPA",
        "riasec_primary": "R",
        "riasec_secondary": "I",
        "streams": ["pcm"],
        "subject_weights": {
            "physics": 0.9,
            "mathematics": 0.8,
            "computerScience": 0.7,
        },
        "workstyle_weights": {
            "building": 0.9,
            "structured": 0.7,
            "researching": 0.6,
        },
        "priority_alignment": ["High Salary", "Job Stability"],
        "sector": "private",
        "cost_level": "high",
        "requires_relocation": True,
        "reason": "VLSI and semiconductor engineers design the chips that power everything from smartphones to supercomputers, working at the nanometer scale where physics meets logic. If you enjoy physics, digital electronics, and meticulous design work, this career places you at the heart of the global technology supply chain.",
    },

    {
        "title": "Bioinformatics Specialist",
        "salary": "₹5–18 LPA",
        "riasec_primary": "I",
        "riasec_secondary": "R",
        "streams": ["pcb", "pcmb"],
        "subject_weights": {
            "biology": 0.85,
            "mathematics": 0.7,
            "computerScience": 0.8,
            "chemistry": 0.4,
        },
        "workstyle_weights": {
            "researching": 0.9,
            "building": 0.5,
            "structured": 0.5,
        },
        "priority_alignment": ["Intellectual Challenge", "Creativity"],
        "sector": "private",
        "cost_level": "high",
        "requires_relocation": True,
        "reason": "Bioinformatics Specialists decode biological data using computational tools — analysing genomes, protein structures, and drug interactions. This interdisciplinary career is tailor-made for someone who loves both biology and programming and wants to accelerate discoveries in medicine and life sciences.",
    },

    {
        "title": "Genetic Counsellor",
        "salary": "₹5–16 LPA",
        "riasec_primary": "I",
        "riasec_secondary": "S",
        "streams": ["pcb"],
        "subject_weights": {
            "biology": 0.95,
            "chemistry": 0.5,
            "psychology": 0.6,
        },
        "workstyle_weights": {
            "researching": 0.7,
            "helping": 0.85,
            "structured": 0.4,
        },
        "priority_alignment": ["Social Impact", "Intellectual Challenge"],
        "sector": "private",
        "cost_level": "high",
        "requires_relocation": True,
        "reason": "Genetic Counsellors help individuals and families understand inherited conditions, interpret genetic test results, and make informed health decisions. If you are drawn to biology and also care deeply about people's well-being, this career combines scientific expertise with compassionate patient guidance.",
    },

    {
        "title": "Food Technologist",
        "salary": "₹4–12 LPA",
        "riasec_primary": "R",
        "riasec_secondary": "I",
        "streams": ["pcb", "pcmb"],
        "subject_weights": {
            "chemistry": 0.85,
            "biology": 0.8,
            "physics": 0.3,
        },
        "workstyle_weights": {
            "building": 0.7,
            "researching": 0.7,
            "fieldwork": 0.5,
            "structured": 0.4,
        },
        "priority_alignment": ["Job Stability", "Social Impact"],
        "sector": "private",
        "cost_level": "medium",
        "requires_relocation": False,
        "reason": "Food Technologists develop, test, and improve food products — ensuring safety, nutrition, and taste at industrial scale. This hands-on career suits science students who enjoy lab work and want to see their innovations reach millions of consumers.",
    },

    {
        "title": "Astrobiologist",
        "salary": "₹6–20 LPA",
        "riasec_primary": "I",
        "riasec_secondary": "R",
        "streams": ["pcb", "pcmb"],
        "subject_weights": {
            "biology": 0.9,
            "physics": 0.7,
            "chemistry": 0.7,
            "mathematics": 0.4,
        },
        "workstyle_weights": {
            "researching": 0.95,
            "fieldwork": 0.5,
            "creative": 0.3,
        },
        "priority_alignment": ["Intellectual Challenge", "Creativity"],
        "sector": "study",
        "cost_level": "high",
        "requires_relocation": True,
        "reason": "Astrobiologists investigate the possibility of life beyond Earth, studying extreme environments and planetary chemistry. This highly research-driven career is perfect for deeply curious minds who want to tackle one of science's most profound questions.",
    },

    {
        "title": "Marine Biologist",
        "salary": "₹4–14 LPA",
        "riasec_primary": "I",
        "riasec_secondary": "R",
        "streams": ["pcb"],
        "subject_weights": {
            "biology": 0.95,
            "chemistry": 0.5,
            "geography": 0.4,
        },
        "workstyle_weights": {
            "researching": 0.85,
            "fieldwork": 0.8,
            "creative": 0.2,
        },
        "priority_alignment": ["Intellectual Challenge", "Social Impact"],
        "sector": "study",
        "cost_level": "high",
        "requires_relocation": True,
        "reason": "Marine Biologists study ocean ecosystems, coral reefs, and aquatic species — often spending time on field expeditions and in coastal labs. If you love biology and the natural world and don't mind outdoor fieldwork, this career lets you contribute to ocean conservation and discovery.",
    },

    {
        "title": "Veterinary Doctor / Animal Surgeon",
        "salary": "₹5–18 LPA",
        "riasec_primary": "S",
        "riasec_secondary": "I",
        "streams": ["pcb"],
        "subject_weights": {
            "biology": 0.95,
            "chemistry": 0.7,
            "physics": 0.3,
        },
        "workstyle_weights": {
            "helping": 0.9,
            "researching": 0.5,
            "fieldwork": 0.6,
            "building": 0.3,
        },
        "priority_alignment": ["Social Impact", "Job Stability"],
        "sector": "private",
        "cost_level": "high",
        "requires_relocation": True,
        "reason": "Veterinary Doctors diagnose and treat animals, perform surgeries, and safeguard public health through disease control. This career is ideal for compassionate biology students who feel a calling to care for animals and are willing to invest in an intensive professional degree.",
    },

    {
        "title": "Renewable Energy Consultant",
        "salary": "₹5–15 LPA",
        "riasec_primary": "I",
        "riasec_secondary": "E",
        "streams": ["pcm"],
        "subject_weights": {
            "physics": 0.85,
            "mathematics": 0.6,
            "chemistry": 0.5,
        },
        "workstyle_weights": {
            "researching": 0.7,
            "fieldwork": 0.6,
            "leading": 0.5,
            "structured": 0.4,
        },
        "priority_alignment": ["Social Impact", "Intellectual Challenge"],
        "sector": "private",
        "cost_level": "medium",
        "requires_relocation": False,
        "reason": "Renewable Energy Consultants advise organisations on transitioning to solar, wind, and other clean energy sources — combining engineering knowledge with business strategy. If you care about climate change and enjoy applied physics, this career lets you make a measurable environmental impact.",
    },

    {
        "title": "Blockchain Developer",
        "salary": "₹8–28 LPA",
        "riasec_primary": "I",
        "riasec_secondary": "R",
        "streams": ["pcm"],
        "subject_weights": {
            "computerScience": 0.95,
            "mathematics": 0.8,
            "physics": 0.2,
        },
        "workstyle_weights": {
            "building": 0.9,
            "researching": 0.7,
            "structured": 0.5,
            "creative": 0.3,
        },
        "priority_alignment": ["High Salary", "Intellectual Challenge"],
        "sector": "private",
        "cost_level": "medium",
        "requires_relocation": False,
        "reason": "Blockchain Developers build decentralised applications, smart contracts, and cryptographic protocols that underpin Web3 and digital finance. If you enjoy deep coding, cryptography, and working in a fast-evolving ecosystem, this high-demand role offers exceptional earning potential.",
    },

    {
        "title": "Financial Risk Manager (FRM)",
        "salary": "₹7–24 LPA",
        "riasec_primary": "C",
        "riasec_secondary": "I",
        "streams": ["comm"],
        "subject_weights": {
            "mathematics": 0.85,
            "economics": 0.8,
            "accountancy": 0.7,
            "businessStudies": 0.4,
        },
        "workstyle_weights": {
            "structured": 0.9,
            "researching": 0.7,
            "leading": 0.3,
        },
        "priority_alignment": ["High Salary", "Job Stability"],
        "sector": "private",
        "cost_level": "medium",
        "requires_relocation": False,
        "reason": "Financial Risk Managers identify, quantify, and mitigate risks that could threaten an organisation's financial health — from market volatility to credit defaults. This career rewards strong quantitative skills and meticulous analysis, offering stability and high compensation in the banking and financial services sector.",
    },

    {
        "title": "Actuarial Analyst",
        "salary": "₹8–35 LPA",
        "riasec_primary": "C",
        "riasec_secondary": "I",
        "streams": ["comm", "pcm"],
        "subject_weights": {
            "mathematics": 0.95,
            "economics": 0.6,
            "accountancy": 0.5,
            "computerScience": 0.4,
        },
        "workstyle_weights": {
            "structured": 0.9,
            "researching": 0.8,
            "building": 0.3,
        },
        "priority_alignment": ["High Salary", "Intellectual Challenge"],
        "sector": "private",
        "cost_level": "medium",
        "requires_relocation": False,
        "reason": "Actuarial Analysts use advanced mathematics and statistics to model financial risk for insurance, pensions, and investment firms. If you have exceptional quantitative ability and enjoy structured, detail-oriented work, this profession is among the highest-paid and most respected in the finance world.",
    },

    {
        "title": "Stock Broker / Portfolio Manager",
        "salary": "₹6–22 LPA",
        "riasec_primary": "E",
        "riasec_secondary": "C",
        "streams": ["comm"],
        "subject_weights": {
            "economics": 0.85,
            "accountancy": 0.7,
            "mathematics": 0.7,
            "businessStudies": 0.5,
        },
        "workstyle_weights": {
            "leading": 0.8,
            "structured": 0.6,
            "researching": 0.6,
        },
        "priority_alignment": ["High Salary", "Leadership"],
        "sector": "private",
        "cost_level": "medium",
        "requires_relocation": False,
        "reason": "Stock Brokers and Portfolio Managers analyse markets, manage investment portfolios, and make high-stakes decisions that directly affect wealth creation. This fast-paced career is ideal for confident, enterprising individuals who thrive under pressure and have a strong grasp of economics and financial markets.",
    },

    {
        "title": "Forensic Accountant",
        "salary": "₹5–18 LPA",
        "riasec_primary": "C",
        "riasec_secondary": "I",
        "streams": ["comm"],
        "subject_weights": {
            "accountancy": 0.95,
            "economics": 0.5,
            "mathematics": 0.6,
            "businessStudies": 0.4,
        },
        "workstyle_weights": {
            "structured": 0.9,
            "researching": 0.8,
            "helping": 0.2,
        },
        "priority_alignment": ["Job Stability", "Intellectual Challenge"],
        "sector": "private",
        "cost_level": "medium",
        "requires_relocation": False,
        "reason": "Forensic Accountants investigate financial fraud, embezzlement, and white-collar crime by tracing money trails through complex accounts. If you have a sharp eye for detail, enjoy detective-style work, and love accounting, this niche career combines investigative thinking with financial expertise.",
    },

    {
        "title": "E-commerce Operations Specialist",
        "salary": "₹4–12 LPA",
        "riasec_primary": "C",
        "riasec_secondary": "E",
        "streams": ["comm"],
        "subject_weights": {
            "businessStudies": 0.8,
            "economics": 0.5,
            "mathematics": 0.5,
            "computerScience": 0.4,
        },
        "workstyle_weights": {
            "structured": 0.8,
            "leading": 0.5,
            "building": 0.4,
        },
        "priority_alignment": ["Job Stability", "Work Life Balance"],
        "sector": "private",
        "cost_level": "low",
        "requires_relocation": False,
        "reason": "E-commerce Operations Specialists manage product listings, logistics coordination, and fulfilment pipelines for online retail platforms. This career suits organised, process-driven individuals who enjoy optimising workflows and keeping digital storefronts running smoothly.",
    },

    {
        "title": "Corporate Lawyer",
        "salary": "₹6–28 LPA",
        "riasec_primary": "E",
        "riasec_secondary": "C",
        "streams": ["arts", "comm"],
        "subject_weights": {
            "english": 0.85,
            "politicalScience": 0.7,
            "economics": 0.5,
            "history": 0.4,
        },
        "workstyle_weights": {
            "leading": 0.8,
            "structured": 0.7,
            "researching": 0.6,
        },
        "priority_alignment": ["High Salary", "Leadership"],
        "sector": "private",
        "cost_level": "high",
        "requires_relocation": True,
        "reason": "Corporate Lawyers advise businesses on mergers, contracts, compliance, and intellectual property — combining sharp legal reasoning with commercial acumen. If you are articulate, persuasive, and enjoy navigating complex regulations, this high-stakes career offers strong financial rewards and professional prestige.",
    },

    {
        "title": "Environmental Lawyer",
        "salary": "₹5–20 LPA",
        "riasec_primary": "E",
        "riasec_secondary": "I",
        "streams": ["arts", "pcm", "pcb", "pcmb"],
        "subject_weights": {
            "english": 0.8,
            "politicalScience": 0.7,
            "geography": 0.6,
            "biology": 0.4,
        },
        "workstyle_weights": {
            "leading": 0.7,
            "researching": 0.7,
            "helping": 0.5,
            "fieldwork": 0.3,
        },
        "priority_alignment": ["Social Impact", "Intellectual Challenge"],
        "sector": "private",
        "cost_level": "high",
        "requires_relocation": True,
        "reason": "Environmental Lawyers advocate for ecological protection, represent communities affected by pollution, and shape green policy through litigation and regulation. This career is ideal for someone passionate about both law and the environment who wants to drive systemic change.",
    },

    {
        "title": "Public Policy Analyst",
        "salary": "₹5–18 LPA",
        "riasec_primary": "I",
        "riasec_secondary": "S",
        "streams": ["arts"],
        "subject_weights": {
            "politicalScience": 0.9,
            "economics": 0.7,
            "english": 0.6,
            "history": 0.5,
            "sociology": 0.5,
        },
        "workstyle_weights": {
            "researching": 0.9,
            "structured": 0.5,
            "helping": 0.5,
            "leading": 0.3,
        },
        "priority_alignment": ["Social Impact", "Intellectual Challenge"],
        "sector": "govt",
        "cost_level": "medium",
        "requires_relocation": True,
        "reason": "Public Policy Analysts research societal issues, evaluate government programmes, and draft evidence-based recommendations that influence legislation and public spending. If you care about social justice and enjoy rigorous analysis of political and economic systems, this career puts your intellect to work for the public good.",
    },

    {
        "title": "Forensic Psychologist",
        "salary": "₹4–16 LPA",
        "riasec_primary": "I",
        "riasec_secondary": "S",
        "streams": ["arts", "pcb", "pcmb"],
        "subject_weights": {
            "psychology": 0.95,
            "biology": 0.4,
            "sociology": 0.5,
            "english": 0.4,
        },
        "workstyle_weights": {
            "researching": 0.8,
            "helping": 0.7,
            "structured": 0.4,
            "fieldwork": 0.3,
        },
        "priority_alignment": ["Intellectual Challenge", "Social Impact"],
        "sector": "private",
        "cost_level": "high",
        "requires_relocation": True,
        "reason": "Forensic Psychologists apply psychological science to the legal system — profiling offenders, assessing witness credibility, and aiding criminal investigations. This career suits deeply analytical individuals who are fascinated by human behaviour and want to contribute to justice and rehabilitation.",
    },

    {
        "title": "Digital Marketing Strategist",
        "salary": "₹5–18 LPA",
        "riasec_primary": "E",
        "riasec_secondary": "A",
        "streams": ["arts", "comm"],
        "subject_weights": {
            "english": 0.7,
            "businessStudies": 0.7,
            "economics": 0.4,
            "psychology": 0.4,
        },
        "workstyle_weights": {
            "creative": 0.8,
            "leading": 0.7,
            "researching": 0.5,
            "structured": 0.3,
        },
        "priority_alignment": ["Creativity", "High Salary"],
        "sector": "private",
        "cost_level": "low",
        "requires_relocation": False,
        "reason": "Digital Marketing Strategists plan and execute online campaigns — leveraging SEO, social media, and data analytics to grow brands and drive revenue. If you are creative, persuasive, and enjoy blending storytelling with data, this career offers rapid growth in the booming digital economy.",
    },

    {
        "title": "Brand Manager",
        "salary": "₹7–22 LPA",
        "riasec_primary": "E",
        "riasec_secondary": "A",
        "streams": ["comm", "arts"],
        "subject_weights": {
            "businessStudies": 0.85,
            "economics": 0.5,
            "english": 0.6,
            "psychology": 0.4,
        },
        "workstyle_weights": {
            "leading": 0.85,
            "creative": 0.7,
            "researching": 0.5,
            "structured": 0.3,
        },
        "priority_alignment": ["Leadership", "Creativity"],
        "sector": "private",
        "cost_level": "medium",
        "requires_relocation": False,
        "reason": "Brand Managers own the identity and market positioning of products — orchestrating advertising, packaging, pricing, and consumer research. This career rewards enterprising leaders with a creative streak who can translate consumer insights into compelling brand strategies.",
    },

    {
        "title": "Sports Manager",
        "salary": "₹4–15 LPA",
        "riasec_primary": "E",
        "riasec_secondary": "S",
        "streams": ["arts", "comm"],
        "subject_weights": {
            "businessStudies": 0.7,
            "english": 0.5,
            "economics": 0.4,
            "psychology": 0.3,
        },
        "workstyle_weights": {
            "leading": 0.85,
            "helping": 0.5,
            "fieldwork": 0.6,
            "creative": 0.3,
        },
        "priority_alignment": ["Leadership", "Work Life Balance"],
        "sector": "private",
        "cost_level": "medium",
        "requires_relocation": True,
        "reason": "Sports Managers handle athlete representation, event logistics, and franchise operations — serving as the business backbone of the sports industry. If you are a natural leader with a love for sports and strong organisational skills, this career lets you turn that passion into a profession.",
    },

    {
        "title": "HR Analytics Specialist",
        "salary": "₹5–16 LPA",
        "riasec_primary": "C",
        "riasec_secondary": "S",
        "streams": ["comm", "arts"],
        "subject_weights": {
            "mathematics": 0.6,
            "businessStudies": 0.7,
            "psychology": 0.6,
            "economics": 0.4,
        },
        "workstyle_weights": {
            "structured": 0.8,
            "researching": 0.7,
            "helping": 0.5,
        },
        "priority_alignment": ["Work Life Balance", "Job Stability"],
        "sector": "private",
        "cost_level": "low",
        "requires_relocation": False,
        "reason": "HR Analytics Specialists use data to improve hiring, retention, and employee engagement — translating workforce patterns into actionable strategies. If you enjoy working with people-centric data and want a structured yet impactful corporate role, this career blends human resources expertise with analytical rigour.",
    },

    {
        "title": "Product Manager",
        "salary": "₹8–26 LPA",
        "riasec_primary": "E",
        "riasec_secondary": "I",
        "streams": ["comm", "pcm"],
        "subject_weights": {
            "businessStudies": 0.8,
            "mathematics": 0.5,
            "computerScience": 0.5,
            "economics": 0.5,
            "english": 0.4,
        },
        "workstyle_weights": {
            "leading": 0.9,
            "creative": 0.6,
            "researching": 0.6,
            "structured": 0.4,
        },
        "priority_alignment": ["Leadership", "High Salary"],
        "sector": "private",
        "cost_level": "medium",
        "requires_relocation": False,
        "reason": "Product Managers define what gets built, prioritise features, and align engineering, design, and business teams around a shared vision. If you enjoy leading without formal authority, making data-informed decisions, and shaping products that users love, this career combines strategic thinking with hands-on execution.",
    },

    {
        "title": "Wildlife Biologist",
        "salary": "₹4–12 LPA",
        "riasec_primary": "I",
        "riasec_secondary": "R",
        "streams": ["pcb"],
        "subject_weights": {
            "biology": 0.95,
            "geography": 0.5,
            "chemistry": 0.4,
        },
        "workstyle_weights": {
            "researching": 0.85,
            "fieldwork": 0.9,
            "helping": 0.3,
        },
        "priority_alignment": ["Social Impact", "Intellectual Challenge"],
        "sector": "govt",
        "cost_level": "medium",
        "requires_relocation": True,
        "reason": "Wildlife Biologists study animal behaviour, track populations, and design conservation strategies — often working in forests, wetlands, and national parks. If you love nature, enjoy outdoor fieldwork, and want to protect biodiversity, this career turns your passion for the living world into meaningful conservation action.",
    },

    {
        "title": "Fashion Designer",
        "salary": "₹4–18 LPA",
        "riasec_primary": "A",
        "riasec_secondary": "E",
        "streams": ["arts", "pcm", "pcb", "pcmb", "comm"],
        "subject_weights": {
            "fineArts": 0.95,
            "english": 0.4,
            "businessStudies": 0.3,
        },
        "workstyle_weights": {
            "creative": 0.95,
            "building": 0.6,
            "leading": 0.3,
            "fieldwork": 0.2,
        },
        "priority_alignment": ["Creativity", "High Salary"],
        "sector": "private",
        "cost_level": "high",
        "requires_relocation": True,
        "reason": "Fashion Designers conceptualise garments, select fabrics, and create collections that reflect cultural trends and personal artistic vision. If you have a strong aesthetic sense, love sketching and colour, and dream of seeing your designs on people, this career channels artistic talent into a vibrant industry.",
    },

    {
        "title": "Animator / 3D Artist",
        "salary": "₹4–15 LPA",
        "riasec_primary": "A",
        "riasec_secondary": "R",
        "streams": ["arts", "pcm", "pcb", "pcmb", "comm"],
        "subject_weights": {
            "fineArts": 0.9,
            "computerScience": 0.6,
            "physics": 0.3,
        },
        "workstyle_weights": {
            "creative": 0.95,
            "building": 0.7,
            "researching": 0.3,
        },
        "priority_alignment": ["Creativity", "Work Life Balance"],
        "sector": "private",
        "cost_level": "medium",
        "requires_relocation": False,
        "reason": "Animators and 3D Artists bring characters, worlds, and visual effects to life for films, games, and advertising. If you have artistic talent, enjoy digital tools, and want a career where imagination is your primary raw material, animation offers a creatively fulfilling path with growing global demand.",
    },

    {
        "title": "International Relations Specialist",
        "salary": "₹5–20 LPA",
        "riasec_primary": "I",
        "riasec_secondary": "E",
        "streams": ["arts"],
        "subject_weights": {
            "politicalScience": 0.9,
            "history": 0.7,
            "english": 0.7,
            "economics": 0.5,
            "geography": 0.4,
        },
        "workstyle_weights": {
            "researching": 0.8,
            "leading": 0.6,
            "structured": 0.4,
            "helping": 0.3,
        },
        "priority_alignment": ["Intellectual Challenge", "Social Impact"],
        "sector": "govt",
        "cost_level": "high",
        "requires_relocation": True,
        "reason": "International Relations Specialists analyse geopolitical trends, advise on foreign policy, and represent national interests in diplomacy and multilateral organisations. If you are fascinated by global affairs, enjoy research and persuasion, and aspire to shape how nations interact, this career offers intellectual depth and significant societal influence.",
    },
]
